<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="9" failures="0" skipped="0" tests="9" time="0.519" timestamp="2025-03-12T19:31:36.746840-04:00" hostname="DESKTOP-CAP26S7"><testcase classname="" name="tests.common_utils.test_aws" time="0.000"><error message="collection failure">ImportError while importing test module '/home/arice/workspaces/reference-python-project/tests/common_utils/test_aws.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/common_utils/test_aws.py:6: in &lt;module&gt;
    import boto3
E   ModuleNotFoundError: No module named 'boto3'</error></testcase><testcase classname="" name="tests.common_utils.test_aws_secrets_rotation" time="0.000"><error message="collection failure">ImportError while importing test module '/home/arice/workspaces/reference-python-project/tests/common_utils/test_aws_secrets_rotation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/common_utils/test_aws_secrets_rotation.py:6: in &lt;module&gt;
    import boto3
E   ModuleNotFoundError: No module named 'boto3'</error></testcase><testcase classname="" name="tests.initialization.test_init_project" time="0.000"><error message="collection failure">ImportError while importing test module '/home/arice/workspaces/reference-python-project/tests/initialization/test_init_project.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/initialization/test_init_project.py:20: in &lt;module&gt;
    import init_project
scripts/init_project.py:41: in &lt;module&gt;
    from template_utils import (
E   ImportError: cannot import name 'print_success' from 'template_utils' (/home/arice/workspaces/reference-python-project/scripts/template_utils.py)</error></testcase><testcase classname="" name="tests.test_aws_mocking_example" time="0.000"><error message="collection failure">ImportError while importing test module '/home/arice/workspaces/reference-python-project/tests/test_aws_mocking_example.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_aws_mocking_example.py:14: in &lt;module&gt;
    import boto3
E   ModuleNotFoundError: No module named 'boto3'</error></testcase><testcase classname="" name="tests.test_init_project" time="0.000"><error message="collection failure">ImportError while importing test module '/home/arice/workspaces/reference-python-project/tests/test_init_project.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_init_project.py:9: in &lt;module&gt;
    from init_project import (
scripts/init_project.py:41: in &lt;module&gt;
    from template_utils import (
E   ImportError: cannot import name 'print_success' from 'template_utils' (/home/arice/workspaces/reference-python-project/scripts/template_utils.py)</error></testcase><testcase classname="" name="tests.unit.aws_mocking_examples.test_aws_integration" time="0.000"><error message="collection failure">ImportError while importing test module '/home/arice/workspaces/reference-python-project/tests/unit/aws_mocking_examples/test_aws_integration.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/aws_mocking_examples/test_aws_integration.py:13: in &lt;module&gt;
    import boto3
E   ModuleNotFoundError: No module named 'boto3'</error></testcase><testcase classname="" name="tests.unit.aws_mocking_examples.test_dynamodb_operations" time="0.000"><error message="collection failure">ImportError while importing test module '/home/arice/workspaces/reference-python-project/tests/unit/aws_mocking_examples/test_dynamodb_operations.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/aws_mocking_examples/test_dynamodb_operations.py:12: in &lt;module&gt;
    import boto3
E   ModuleNotFoundError: No module named 'boto3'</error></testcase><testcase classname="" name="tests.unit.aws_mocking_examples.test_s3_operations" time="0.000"><error message="collection failure">ImportError while importing test module '/home/arice/workspaces/reference-python-project/tests/unit/aws_mocking_examples/test_s3_operations.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/aws_mocking_examples/test_s3_operations.py:12: in &lt;module&gt;
    import boto3
E   ModuleNotFoundError: No module named 'boto3'</error></testcase><testcase classname="" name="tests.unit.spark.test_transformations" time="0.000"><error message="collection failure">ImportError while importing test module '/home/arice/workspaces/reference-python-project/tests/unit/spark/test_transformations.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/spark/test_transformations.py:4: in &lt;module&gt;
    from pyspark.sql import SparkSession
E   ModuleNotFoundError: No module named 'pyspark'</error></testcase></testsuite></testsuites>
